# Copyright Â©2000-2025 Quinn A Michaels; All rights reserved.  
# Legal Signature Required For Lawful Use.  
# Distributed under VLA:38159520729793885324 LICENSE.md

author:
  name: Quinn A Michaels
  email: "quinn@indra.ai"

google_analytics: UA-126646842-1
