# Copyright Â©2002-2025 Quinn A Michaels; All rights reserved.  
# Legal Signature Required For Lawful Use.  
# Distributed under VLA:38478178200141356938 LICENSE.md

author:
  name: Quinn A Michaels
  email: "quinn@indra.ai"

google_analytics: UA-126646842-1
